[package]
name = "master-thesis-experiments"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.0-alpha.1"
clap = { version = "4.5.4", features = ["derive"] }
serde = { version = "1.0.200", features = ["derive"] }
csv = "1.3.0"
chrono = "0.4.38"
indicatif = "0.17.8"
